name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: aws-athena-query-federation_ubuntu-latest_16-core
    strategy:
      matrix:
        java-version: ['11', '17']
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}

      - name: Build Javadoc with Maven
        run: mvn -B javadoc:aggregate --file pom.xml -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN --no-transfer-progress

      - name: Switch to gh-pages branch
        if: ${{ matrix.java-version == '11' }}
        run: |
          git fetch
          git checkout gh-pages

      - name: Remove old files
        if: ${{ matrix.java-version == '11' }}
        run: rm -rf com

      - name: Copy new files
        if: ${{ matrix.java-version == '11' }}
        run: cp -r target/reports/apidocs/* .

      - name: Commit files
        if: ${{ matrix.java-version == '11' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          #add any untracked files in the com dir
          git add com
          #commit only if there is a diff
          git diff-index --quiet HEAD || git commit -m "Syncing javadoc from master:$GITHUB_SHA" -a

      - name: Push changes
        if: ${{ matrix.java-version == '11' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
